version: '3'

services:

  nodejs-container:
    container_name: nodejs-container
    build: '.'
    volumes:
      - .:/home/node/api
      - /home/node/api/node_modules
    depends_on:
      - postgres-container
      - mongo-container
    networks:
      - app-connect
    ports:
      - '3333:3333'

  mongo-container:
    container_name: mongo-container
    image: 'mongo'
    restart: unless-stopped
    volumes:
      - mongo-container-data:/data
    ports:
      - '27017:27017'
    networks:
      - app-connect

  postgres-container:
    container_name: postgres-container
    image: postgres:11
    restart: unless-stopped
    volumes:
      - postgres-container-data:/data
    environment: 
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS} 
    networks:
      - app-connect

volumes:
  postgres-container-data:
  mongo-container-data:

networks:
  app-connect:
      driver: bridge